### ISSUE TITLE
http 404 error

### ISSUE THREAD

**Issue by taduvai35** [esoxjem/MovieGuide#100]
movie data isnt loading in our activity.

**Comment by esoxjem** [comment]
Did you add your themoviedb.org API key in the local.properties file:
```
tmdb_api_key=YOUR_API_KEY
```

**Comment by taduvai35** [comment]
no, how to do that setup process

Tsrg

**Comment by esoxjem** [comment]
Get a developer key from [themoviedb.org](https://www.themoviedb.org/documentation/api) and add in the local.properties file:
```
tmdb_api_key=YOUR_API_KEY
```

**Comment by taduvai35** [comment]
im getting like this, aftr open the app

Tsrg
