### ISSUE TITLE
question for contribution

### ISSUE THREAD

**Issue by dtree0520** [esoxjem/MovieGuide#101]
i'm korean university student.
Recently, i used movieguide application in android. i think, it is quite useful and it has good information and interface. So i want our korean to know this application using opensource. But because text file like readme is written in English, people might have trouble in interpreting English.
So can i Translate text file like readme or contributing guidelines into Korean?

**Comment by ChristineWasike** [comment]
Hey @dtree0520 that's an interesting concern you've raised. When you say translate the readme into Korean, do you mind expounding on whether there should be another readme alongside written in Korean? Basically expound on how that experience should be.

**Comment by ChristineWasike** [comment]
I am ready to work on it.

**Comment by dtree0520** [comment]
@ChristineWasike  No. It should be nice if another readme version which is translated into Korean.
So, I hope that a contribution is made if i translate textfile into korean.
First, i already translated readme into Korean

Android app that lists popular/highest-rated movies, shows trailers and reviews.
->이 어플리케이션은 인기 / 최고 등급의 영화를 나열하고 예고편 및 리뷰를 표시하는 Android 어플리케이션입니다.

This app showcases the MVP pattern, RxJava, Dagger 2 and Uncle Bob Martin's Clean Architecture approach. Optimized for tablets.
->이 어플리케이션은 MVP 패턴, RxJava, Dagger 2 및 Uncle Bob Martin 의 Clean Architecture 접근 방식을 보여줍니다. 또한 이 어플리케이션은 태블릿에 최적화 되어있습니다.

Add your themoviedb.org API key in the local.properties file:
->local.properties 파일에 user의 themoviedb.org API 키를 추가하여주십시오.

Check out the Kotlin version here
->here을 눌러서 Kotlin버전을 확인하십시오.

Can you help me by updating readme Korean version?

**Comment by esoxjem** [comment]
Where would we add these translated files to? A different directory?

**Comment by dtree0520** [comment]
Hey @esoxjem I think it is better to add these translated files in same this directory.
So, people can read both original readme file and transltated readme file.
Additionally, what do you think if we  translate another textfile or suggest idea about application?

**Comment by esoxjem** [comment]
Hi @dtree0520, please fork this repo and translate/maintain the Korean version. Thanks.
