### ISSUE TITLE
I found the bug in newest list!

### ISSUE THREAD

**Issue by tjalsrb97** [esoxjem/MovieGuide#102]
I am user to use the movie guide app. Before reporting bugs, it's always helpful to use Movie Guides as a movie lover. But I fount the bug.  I would like to tell you the bug I found in order for movie guide app to go in a good direction. Even if a movie is loaded from the newest list, the same movie is loaded continuously. My wish is that when I load a movie, I want a new movie from before. 

Thank you for reading the long article and I look forward to your reply ^_^

**Comment by tjalsrb97** [comment]
@esoxjem 
Please answer for me once ㅠㅠ

**Comment by esoxjem** [comment]
Hi @tjalsrb97, thanks. I will take a look.

**Comment by esoxjem** [comment]
Already reported in #96
