### ISSUE TITLE
I have a question for your "Movie Guide" application!

### ISSUE THREAD

**Issue by Hyunwoo-CHO** [esoxjem/MovieGuide#104]
Hello! I'm university student from Korea. 
I have a few question about your application, named "Movie Guide".

First, where do you get reviews for movies from? 
Second, what do you think about letting people, users of "Movie Guide" application, write their own reviews for each movies.

Think about my questions and look forward to your thoughtful response.

Thank you for taking the time to read my question!

**Comment by Rajnish23** [comment]
Go through this link - https://www.themoviedb.org/documentation/api
The answer to your question is in this link.

**Comment by esoxjem** [comment]
Thanks @Rajnish23
