### ISSUE TITLE
Using Retrofit 2 with RxJava for network layer 

### ISSUE THREAD

**Issue by mhussien86** [esoxjem/MovieGuide#12]
Less code for network layer as you will not be in any need to write parsers for your response.

**Comment by esoxjem** [comment]
👍

**Comment by mhussien86** [comment]
If you agree on this issue i can make a pull request.

**Comment by esoxjem** [comment]
Sure. Please create a Pull Request against this branch: https://github.com/esoxjem/MovieGuide/tree/feature/retrofit2

**Comment by mhussien86** [comment]
This been long time, the branch is no more exits!, should we create it again?

**Comment by esoxjem** [comment]
@mhussien86 sounds good

**Comment by ivanTrogrlic** [comment]
Hello.
I created a new pull request which fixes this issue, you can check it out here:
https://github.com/esoxjem/MovieGuide/pull/38

**Comment by esoxjem** [comment]
Thanks @ivanTrogrlic
