### ISSUE TITLE
Store favorited movies in Realm

### ISSUE THREAD

**Issue by esoxjem** [esoxjem/MovieGuide#15]

**Comment by Chuckytuh** [comment]
This is something I am very curious to see how Ream integrates with Clean Architecture!

**Comment by esoxjem** [comment]
@Chuckytuh Usually I don't need the change listener that Realm provides on my views so I wrap the result using `Observable.fromCallable()`

**Comment by Chuckytuh** [comment]
So are you saying you apply a mapper to transform from a RealmObject from the callback into a view model object on a Rx stream?

**Comment by ugochukwu** [comment]
@esoxjem Have you already started with this issue?

**Comment by esoxjem** [comment]
@ugochukwu Not yet.
