### ISSUE TITLE
RxUtils.unsubscribe vs CompositeSubscription

### ISSUE THREAD

**Issue by wotomas** [esoxjem/MovieGuide#17]
I am curious, is there a specific reason why you decided to use
```
RxUtils.unsubscribe(trailersSubscription, reviewSubscription);
``` 
over
```
CompositeSubscription unsubscribe()
``` 

:D just curious!

**Comment by esoxjem** [comment]
@wotomas I find creating + adding + unsubscribing from a `CompositeSubscription` every time a bit cumbersome, something that Uncle Bob calls "Temporal Coupling".  Using a utility function seems more succinct.

**Comment by wotomas** [comment]
I see, it makes sense! thanks!
