### ISSUE TITLE
App crashes when I switch to airplane mode and trying to open any movie details

### ISSUE THREAD

**Issue by jkozh** [esoxjem/MovieGuide#20]
A couple of last log lines when app crashes:

> I/InjectionManager: dispatchOnViewCreated > Target : com.esoxjem.movieguide.details.MovieDetailsActivity isFragment :false
> D/SecWifiDisplayUtil: Metadata value : SecSettings2
> D/OkHttp: --> GET http://api.themoviedb.org/3/movie/341174/videos?api_key=my_key http/1.1
> D/OkHttp: Accept: application/json
> D/OkHttp: --> END GET
> D/OkHttp: --> GET http://api.themoviedb.org/3/movie/341174/reviews?api_key=my_key http/1.1
> D/OkHttp: Accept: application/json
> D/OkHttp: --> END GET
> D/ViewRootImpl: #1 mView = com.android.internal.policy.PhoneWindow$DecorView{bf6c185 I.E...... R.....ID 0,0-0,0}
> D/OkHttp: <-- HTTP FAILED: java.net.UnknownHostException: Unable to resolve host "api.themoviedb.org": No address associated with hostname
> D/OkHttp: <-- HTTP FAILED: java.net.UnknownHostException: Unable to resolve host "api.themoviedb.org": No address associated with hostname
> E/AndroidRuntime: **FATAL EXCEPTION: main**
> Process: com.esoxjem.movieguide, PID: 18198

**Comment by esoxjem** [comment]
Thanks @jkozh. #21 should fix this.
