### ISSUE TITLE
Move to an offline-first architecture

### ISSUE THREAD

**Issue by esoxjem** [esoxjem/MovieGuide#30]

**Comment by wotomas** [comment]
Just curious and interested, are you planning to use Realm for implementing offline-first architecture? :D

**Comment by esoxjem** [comment]
@wotomas Yup, I was. But now I'm thinking of trying it out with the latest architecture components.

**Comment by wotomas** [comment]
@esoxjem I see, that sounds interesting 👍 I haven't had time recently to look into it.. should try though 👍
