### ISSUE TITLE
Remove all implements Parcelable from data classes. 

### ISSUE THREAD

**Issue by mhussien86** [esoxjem/MovieGuide#37]
Remove all implemention of Parcelable and add Parceler Library instead.

**Comment by esoxjem** [comment]
@mhussien86 have you tried AutoValue/AutoParcel?

**Comment by Rainer-Lang** [comment]
And AutoGson

**Comment by mhussien86** [comment]
@esoxjem Thats the only Library i have used https://github.com/johncarl81/parceler and its really nice, will have a look over the mentioned libraries.

**Comment by Rainer-Lang** [comment]
You should really look at AutoValue and the extensions.
