### ISSUE TITLE
Implement pagination on the listing screen

### ISSUE THREAD

**Issue by basemnassar11** [esoxjem/MovieGuide#40]
i want to inc number movie more than 20 but not working with me

**Comment by esoxjem** [comment]
@basemnassar11 can you provide some more details? I didn't get you.

**Comment by basemnassar11** [comment]
hi, 
in MoviesListingFragment class, i found list  "private List<Movie> movies = new ArrayList<>(20);" , but if i change number 20 to 40 ex stil movie still movies show 20 not 40 
sorry about english 
thank you

**Comment by esoxjem** [comment]
@basemnassar11 the way to get more movies is to implement pagination and request for the next page from the tmdb API when you reach the end of the list.

**Comment by esoxjem** [comment]
Done https://github.com/esoxjem/MovieGuide/pull/65
