### ISSUE TITLE
Fancy UI

### ISSUE THREAD

**Issue by esoxjem** [esoxjem/MovieGuide#42]
- Look at Plaid
- Shared element transitions
- TextView layout transitions
- etc.

**Comment by Rainer-Lang** [comment]
Great!

**Comment by Rishabhmishra328** [comment]
I would like to contribute in this effort, can I get some guidelines on what is required.

**Comment by esoxjem** [comment]
@Rishabhmishra328  
- Mostly sectioning the home screen into now playing, popular, top rated and upcoming as seen on the official [website](https://www.themoviedb.org/). 
- Adding shared element transitions to the details screen
- Updating the UI to look similar to the [official movie page](https://www.themoviedb.org/movie/284053-thor-ragnarok?language=en).
