### ISSUE TITLE
Replace Gson with Moshi

### ISSUE THREAD

**Issue by meugen** [esoxjem/MovieGuide#44]
Hello. Why do you use two libraries for JSON parsing (Moshi and Gson) in the project?

**Comment by esoxjem** [comment]
@meugen thanks for pointing this out. I was just trying out Moshi some time back. Will remove Gson.

**Comment by TheJackTenor** [comment]
I interested to working at this issue. I have forked the project and learned it. As far as i learn, if we going to replace GSON with Moshi, there is no need to serializing json field name right ? Like, if we using gson, we use annotation SerializedName, but in Moshi, we don't

**Comment by esoxjem** [comment]
@TheJackTenor sure. If your Java field names are same as that in JSON then it is not required. In other cases, you would have to use the `@Json` annotation. Take a look here:
https://github.com/square/moshi#custom-field-names-with-json

**Comment by TheJackTenor** [comment]
@esoxjem Thanks a lot for the sugestion. I have applied it for every Java field names that aren't same as JSON field names. Before that, i also added new library called Converter Moshi and have applied it in Retrofit to replace Converter GSON. The apps works perfectly fine.

**Comment by esoxjem** [comment]
@TheJackTenor great. Send in a Pull Request referencing this issue and I can take a look.

**Comment by TheJackTenor** [comment]
@esoxjem Okay
