### ISSUE TITLE
API KEY

### ISSUE THREAD

**Issue by swarnabho** [esoxjem/MovieGuide#53]
how do i add the api key ? when i run the app it shows an error at runtime.....http 401 unauthorised..is it because of the api being locked ?

**Comment by esoxjem** [comment]
Check the Readme for details

**Comment by swarnabho** [comment]
i am trying to add it but its not working....can u just guide me on how to add the api key ?

**Comment by esoxjem** [comment]
In your root(outermost) directory, there should a `local.properties` file. Add your developer key there:
`tmdb_api_key=......`

**Comment by swarnabho** [comment]
I tried to add the api key ,but im not familiar with the process of adding
an api key to an android app.Should i access the tmdb site and register
there to generate my own api key ?

**Comment by esoxjem** [comment]
Yes

**Comment by swarnabho** [comment]
got it thanks for your help

**Comment by esoxjem** [comment]
Great!

**Comment by andrect1** [comment]
Hello
here?

buildConfigField "String", "TMDB_API_KEY", "\"${getProperty("local.properties", "tmdb_api_key")}\"APY_HEY_HERE?"
        buildConfigField "String", "TMDB_BASE_URL", "\"http://api.themoviedb.org/\""
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"

Only there?

**Comment by esoxjem** [comment]
Yes

**Comment by swarnabho** [comment]
Yes,whats the issue ?

**Comment by andrect1** [comment]
does not work
401 error

**Comment by swarnabho** [comment]
It worked for me when i provided the api key
