### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by Rudloff** [esoxjem/MovieGuide#70]
Hello,

Would you be interested in publishing this app on [F-Droid](https://f-droid.org/)?
It is an app store containing only open-source apps built from source.

(However, [F-Droid does not sign up for any API keys](https://f-droid.org/docs/Inclusion_Policy/) so it would require https://github.com/esoxjem/MovieGuide/issues/69.)

**Comment by esoxjem** [comment]
Hey @Rudloff, not at the moment. Thanks!
