### ISSUE TITLE
First 20 movies loaded twice

### ISSUE THREAD

**Issue by KaveriKR** [esoxjem/MovieGuide#96]
First 20 movies  loaded twice , which appear in  the first screen after the application is opened every time.

I would like to work on it.- Yes

**Comment by esoxjem** [comment]
Thanks

**Comment by KaveriKR** [comment]
#95  solves the issue.

**Comment by tjalsrb97** [comment]
I'm movieguide user.  I usually find bugs because I use movie guides a lot. 
20 movies on the Newest list are still loading after loading not 2 times.

**Comment by tjalsrb97** [comment]
I hope you check it out and reply back.

**Comment by esoxjem** [comment]
@tjalsrb97 should be fixed now
